spring:
  application:
    name: ticket-assistant
  ai:
    vectorstore:
      chroma:
        initialize-schema: true
        client:
          host: localhost
          port: 8000
    ollama:
      embedding:
        options:
          model: nomic-embed-text
      init:
        chat:
          include: false
        pull-model-strategy: WHEN_MISSING
      base-url: http://localhost:11434
server:
  port: 8080

